### ISSUE TITLE
Test does not start: `Cannot find module 'gauge-ts/dist/RunnerServer'`

### ISSUE THREAD

**Issue by mizuochi-hikaru** [getgauge/gauge-ts#184]
**Describe the bug**
I updated this plugin from 0.1.1 to 0.3.3 and an error occurred.
```
[eval].ts(1,23): error TS2307: Cannot find module 'gauge-ts/dist/RunnerServer' or its corresponding type declarations.
Error ----------------------------------

[Gauge]
Error: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.22.2/libexec/src/runtime/debug/stack.go:24 +0x5e
main.recoverPanic()
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/gauge.go:27 +0x34
panic({0x8cdd240?, 0x92b75e0?})
        /usr/local/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x132
github.com/getgauge/gauge/runner.(*GrpcRunner).ExecuteMessageWithTimeout(0xc0004ca302?, 0xc00012a740?)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/runner/grpcRunner.go:197 +0xe
github.com/getgauge/gauge/validation.(*SpecValidator).validateStep(0xc00059a000, 0xc0004a0000)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:345 +0x1a2
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc00059a000, 0xc0004a0000)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:313 +0x3d9
github.com/getgauge/gauge/validation.(*SpecValidator).Step(0xc00059a000, 0xc000614000?)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:307 +0x525
github.com/getgauge/gauge/gauge.(*Specification).Traverse(0xc000614000, {0x8dd6380, 0xc00059a000}, 0xc0003ef8b0)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/gauge/specification.go:261 +0x22f
github.com/getgauge/gauge/validation.(*SpecValidator).validate(0xc00059a000)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:298 +0x55
github.com/getgauge/gauge/validation.(*validator).Validate(0xc0000e99f0)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:284 +0x10a
github.com/getgauge/gauge/validation.ValidateSpecs({0xc0002b6140, 0x1, 0x5}, 0x0)
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/validation/validate.go:174 +0x238
github.com/getgauge/gauge/execution.init.func1({0xc0002b6140, 0x1, 0x5})
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/execution/execute.go:108 +0x1c5
github.com/getgauge/gauge/cmd.execute(0x92cd0e0, {0xc0002b6140, 0x1, 0x5})
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/cmd/run.go:241 +0x368
github.com/getgauge/gauge/cmd.init.func12(0x92cd0e0, {0xc0002b6140, 0x1, 0x5})
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/cmd/run.go:90 +0x1b9
github.com/spf13/cobra.(*Command).execute(0x92cd0e0, {0xc0002b60f0, 0x5, 0x5})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x92cdc60)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/getgauge/gauge/cmd.Parse()
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/cmd/cmd.go:112 +0x26
main.main()
        /private/tmp/gauge-20240507-4662-woh7hw/gauge-1.6.7/gauge.go:19 +0x30

Get Support ----------------------------
        Docs:          https://docs.gauge.org
        Bugs:          https://github.com/getgauge/gauge/issues
        Chat:          https://github.com/getgauge/gauge/discussions

Your Environment Information -----------
        darwin, 1.6.7
        dotnet (0.5.7), html-report (4.3.1), java (0.11.0), js (4.0.1), screenshot (0.2.0), ts (0.3.3)
```
Perhaps this error has occurred in launcher.mjs.
```ts
  const script = `"import { start } from 'gauge-ts/dist/RunnerServer'; start();"`;
```
How can I avoid this?

**To Reproduce**
I could not reproduce in other environments.
It's difficult to show my environment, sorry.

List of things I have tried:
(run `npm i` before each)
- create new project (`gauge init ts`) and run sample => OK
- downgrade this plugin (0.3.3 -> 0.1.1) => OK
- downgrade this plugin (0.3.3 -> 0.3.0) => same error
- re-install gauge (via brew) and retry on 0.3.3  => same error

**Expected behavior**
The runner starts running the test.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [e.g. linux]
 macOS Sonoma 14.5
 - Gauge and plugin version [run `gauge -v`]
```
❯ gauge -v
Gauge version: 1.6.7
Plugins
-------
dotnet (0.5.7)
html-report (4.3.1)
java (0.11.0)
js (4.0.1)
screenshot (0.2.0)
ts (0.3.3)
```
 - Node version [run `node -v`]
```
❯ node -v
v20.14.0
```
 - Npm version [run `npm -v`]
 ```
❯ npm -v 
10.7.0
```

**Additional context**
For example if you are facing an issue with editor (vscode)
 - VS Code Version : [e.g. 1.30.0]
1.90.2 (Universal)
 - Gauge VS Code Plugin Version : [e.g. 0.0.5]
0.1.6

I usually run tests from the terminal, but I also observed that the VSCode plugin failed to start.

**Comment by chadlwilson** [comment]
Can you take a look at https://github.com/getgauge/gauge-ts/issues/179#issuecomment-2164988898 ?

You may need to update the dependency within your package.json to match the plugin version.

**Comment by mizuochi-hikaru** [comment]
Ohhh, package.json was back to the old one...I'm so sorry

**Comment by chadlwilson** [comment]
Yeah, it would be better if such mismatches failed gracefully rather than crashing, but I dont personally have enough knowledge to know whether that is possible.

**Comment by BugDiver** [comment]
We could have a check in the plugin to validate the `gauge-ts` package version and report for mismatch. We do something similar in gauge-python.
https://github.com/getgauge/gauge-python/blob/fcb308d733fb1ceb5f0284c7c5d83909e06aed35/start.sh#L7
